# 아이템 7 : 결과 부족이 발생할 경우 null과 Failure를 사용하라

함수가 원하는 결과를 만들지 못할 때가 있다.

- 서버로부터 데이터를 읽어 들이려고 했는데, 인터넷 연결 문제로 읽어들이지 못한 경우
- 조건에 맞는 첫 번재 요소를 찾으려 했는데, 조건에 맞는 요소가 없는 경우
- 텍스트를 파싱해서 객체를 만들려고 했는데, 텍스트의 형식이 맞지 않는 경우

이런 상황을 처리하는 메커니즘은 크게 다음 두 가지가 있다.

- null 또는 ‘실패를 나타내는 sealed 클래스(일반적으로 Failure라는 이름을 붙인다.)’를 리턴한다.
- 예외를 throw 한다.

위 두 가지는 중요한 차이가 있다. 일단 예외는 정보를 전달하는 방법으로 쓰면 안된다. 

예외는 잘못된 특별한 상황을 나타내고 처리되어야 한다. 예외는 예외적인 상황이 발생했을 때 사용하는 것이 좋다.(이펙티브 자바)

이유를 정리하면 아래와 같다.

- 많은 개발자가 예외가 전파되는 과정을 제대로 추적하지 못한다.
- 코틀린의 모든 예외는 unchecked 예외다. 따라서 사용자가 예외를 처리하지 않을 수도 있으며, 이와 관련된 내용은 문서에도 제대로 드러나지 않는다. 실제로 API를 사용할 때 예외와 관련된 사항을 단순하게 메서드 등을 사용하면서 파악하기 힘들다.
- 예외는 예외적인 상황을 처리하기 위해서 만들어졌으므로 명시적인 테스트만큼 빠르게 동작하지 않는다.
- **try-catch 블록 내부에 코드를 배치하면, 컴파일러가 할 수 있는 최적화가 제한된다.**

첫 번째로 제시한 null과 Failure가 예상되는 오류를 표현할 때 굉장히 좋다. 

명시적이면서 효율적이고 간단한 방법으로 처리할 수 있다.

따라서 충분히 예측할 수 있는 범위의 오류는 null과 Failure를 사용하고, 예측하기 어려운 예외적인 범위의 오류는 예외를 throw해서 처리하는 것이 좋다.

간단한 예를 살펴보자.

```kotlin
inline fun <reified T> String.readobjectOrNull(): T? {
	// ...
	if(incorrectSign) {
		return null
	}

	// ...
	return result
}

inline fun <reified T> String.readObject(): Result<T> {
	// ...
	if(incorrectSign) {
		return Failure(JsonParsingException())
	}
	// ...
	return Success(result)
}

sealed class Result<out T>
class Success<out T>(val result: T): Result<T>()
class Failure<val throwable: Throwable): Result<Nothing>90

class JsonParsingException: Exception()
```

이렇게 표시되는 오류는 다루기 쉽고 놓치기 어렵다. null을 처리해야 한다면 safe call 이나 엘비스 연산자 같은 다양한 null-safety 기능을 활용한다.

Result 같은 union type를 리턴하기로 했다면, when을 이용해 처리할 수도 있다.

```kotlin
val person = userText.readObjectOrNull<Person>()
val age = when(person) {
		is Success -> person.age
		is Failure -> -1
}
```

이런 오류 처리 방식은 try-catch 블록보다 효율적이며, 사용하기 쉽고 더 명확합니다. null 값과 sealed result 클래스는 명시적으로 처리되야 하며, 애플리케이션 흐름을 중지하지도 않는다.

++ 추가적인 정보를 전달해야 한다면 sealed result를 사용하고, 그렇지 않으면 null을 사용하는게 일반적이다. Failure를 처리할 때 필요한 정보를 가질 수 있다는 걸 기억하자.

일반적으로 두 가지 형태의 함수를 사용한다. 하나는 예측할 수 있을 대, 다른 하나는 예상할 수 없을 때 쓴다.

List는 두 가지 모두를 갖고 있으므로 이를 기반으로 살펴보자.

- get : 측정 위치에 있는 요소를 추출할 때 사용한다. 만약 요소가 해당 위치에 없다면 IndexOutOfBoundsException을 터트림
- getOrNull: out of range 오류가 발생할 수 있는 경우에 사용한다. 발생할 경우 null을 리턴한다.